### ISSUE TITLE
Query parameters not properly urlencoded

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion-node#13] opened 2016-06-30 21:25 UTC
If I try to query using $between and $gt, flask-authlib throws:

```
ValueError: Error trying to decode a non urlencoded string. Found invalid characters: {'$', ':'} in the string: 'page=1&per_page=500&sort=%7B%22created_at%22:false%7D&where=%7B%22A%22:%221%22,%22created_at%22:%7B%22$between%22:%22%5B%5C%222016-06-28T21:18:16.096Z%5C%22,%5C%222016-06-30T21:18:16.098Z%5C%22%5D%22%7D%7D'. Please ensure the request/response body is x-www-form-urlencoded.
```

My query:

```
A.query(
    {
    where: {
       A: 1,
       created_at = {
              $between: [date_range.start, date_range.end]
              }
   },
   sort: {"created_at": true},
   per_page: 500
   },
   {
   paginate: true
   });
```

**Comment by rolandjitsu** [comment] 2016-07-04 08:34
@Alain1405 I will investigate this on Wednesday.

**Comment by rolandjitsu** [comment] 2016-07-07 07:37
@Alain1405 a couple of things:

``` js
A.query(
    {
    where: {
       A: 1,
       created_at = {
              $between: [date_range.start, date_range.end]
              }
   },
   sort: {"created_at": true},
   per_page: 500
   },
   {
   paginate: true
   });
```

is not valid JS, perhaps you wanted:

``` js
A.query({
    where: {
        createdAt: {$between: [date_range.start, date_range.end]},
        'A': 1
    },
    sort: {createdAt: true},
    perPage: 500
}, {
    paginate: true
});
```

And there is not need to use underscore case (`created_at`) for query props, you can use camel case (`createdAt`) and it will be automatically converted so that the potion backend can understand it.

As for the error you get, it might not be a problem within the library, but I am writing some tests right now just to make sure of it.

**Comment by rolandjitsu** [comment] 2016-07-07 08:10
So, running `decodeURI` on your string will give me the following:

``` js
let decodedURI = decodeURI('page=1&per_page=500&sort=%7B%22created_at%22:false%7D&where=%7B%22A%22:%221%22,%22created_at%22:%7B%22$between%22:%22%5B%5C%222016-06-28T21:18:16.096Z%5C%22,%5C%222016-06-30T21:18:16.098Z%5C%22%5D%22%7D%7D')
// "page=1&per_page=500&sort={"created_at":false}&where={"A":"1","created_at":{"$between":"[\"2016-06-28T21:18:16.096Z\",\"2016-06-30T21:18:16.098Z\"]"}}"
```

I can see the problem occurs when the array is read as a string. I'm not quite sure how you got there, but if I try to make a query with:

``` js
{
    where: {
        createdAt: {$between: [0, 1]}
    }
}
```

What I get back if I run `decodeURI` is `'/user?where={"created_at":{"$between":[0,1]}}'` which is valid.

On top of that, the serialization of the query params is done by Angular, so if there were a problem it might be within Angular, but that's not the case.

Furthermore, we actually use this lib in our internal projects (together with Angular 1) and there are queries with what you describe, but we did not encounter the same problem, so it must be something you are doing wrong along the way.

I shall be closing this as I cannot reproduce, if you can write a plunk or something to illustrate the problem, please fell free to reopen the issue.

**Closed as completed by rolandjitsu** 2016-07-07 08:10 UTC
Labels: Bug
