### ISSUE TITLE
Add support for UUID as $id

### ISSUE THREAD

**Issue by galuszkak** [biosustain/potion-node#20] opened 2017-03-26 07:26 UTC
For now, if one database is used uuid, potion-node will incorrectly deserialize ID.

**Comment by rolandjitsu** [comment] 2017-03-26 14:14
@galuszkak check if this is fixed with https://github.com/biosustain/potion-node/commit/3b20d9c0c66b636cbb179efa6ec4404dbb6f447b.

**Comment by galuszkak** [comment] 2017-03-26 16:08
@rolandjitsu testing now 👍 , will let You know.

**Comment by rolandjitsu** [comment] 2017-03-26 16:25
Note that the impl. for AngularJS might not work due to some breaking changes. I'm working on providing a backwards compatible fix.

**Comment by galuszkak** [comment] 2017-03-26 17:18
@rolandjitsu  I'm using Angular 2 now.

So I'm stuck right now I've encounter problem with save() method. (update works fine).

```
{message: "Additional properties are not allowed ('potion' was unexpected)", path: [],…}
path:[]
validationOf:{additionalProperties: false}
```

**Comment by rolandjitsu** [comment] 2017-03-26 17:52
@galuszkak I see, I know what the issue is. Soon a fix will be pushed.

**NOTE**: You have to use Angular 4 as the `v1` and above will only be compatible with that. But it might just work with Angular 2 as well (though I doubt it, because instead of `OpaqueToken` - which is deprecated - I use `InjectionToken`).

**Comment by galuszkak** [comment] 2017-03-26 18:12
I'm using Angular 4 (sorry forgot that I did upgrade to new release) it's kinda misleading with so often changing versions of angular :).

@rolandjitsu awesome if I can help You somehow just let me know.

**Comment by rolandjitsu** [comment] 2017-03-26 18:27
No worries, I have the same struggles at times. I've just pushed some changes again. Let me know if it works now.

**Comment by galuszkak** [comment] 2017-03-26 18:37
@rolandjitsu for some reason now I started getting on save/update `status_code=409, Conflict`. I don't see big change in requests but maybe I'm missing something.

**Comment by rolandjitsu** [comment] 2017-03-26 19:20
It sounds like you are trying to save a resource that already exists. How are you using `.save()`?

**Comment by galuszkak** [comment] 2017-03-27 04:27
OK It works now, but I have strange issue right now. Properties from server and locally never match. 

Example I have display_name field on my Item. After save it changes to displayName. Is this expected behaviour? It's quite confusing for now.

**Comment by galuszkak** [comment] 2017-03-27 05:45
After playing it a while it make sense for me now. :)

**Comment by galuszkak** [comment] 2017-03-27 05:52
For API argument. It's misleading how save works. Probably (I don't have a data so it's maybe only my mind) most users could assume (like myself ;) ) it should work like an upsert (detect if it's creation/or update) and do appropriate action (POST|PATCH) and for now that isn't a case. I just stumble upon that and wasn't sure why is that.

But besides, this library is AWESOME! Love it 👍  awesome work @rolandjitsu :)

**Comment by rolandjitsu** [comment] 2017-03-27 09:05
@galuszkak All properties are converted from snake case to camel case (and the other way around when a request is made), it's a convention that the library follows. Perhaps it should have been mentioned in the docs.

As for `.save()`, it's by design. Perhaps it might be worth looking into an implementation of `Item` where `.save()` can act as an update if the resource already exists.
@lyschoening what do you think? Is this something we should support?

Glad you like the lib, but this was a team work.

**Comment by rolandjitsu** [comment] 2017-03-27 09:07
Closed with https://github.com/biosustain/potion-node/commit/3b20d9c0c66b636cbb179efa6ec4404dbb6f447b.

**Closed as completed by rolandjitsu** 2017-03-27 09:07 UTC
Labels: Feature

**Comment by lyschoening** [comment] 2017-03-27 09:10
@rolandjitsu I actually thought it acted as an update if the object has an uri :) The predecessor of this library behaved that way and the Python implementation does too. https://github.com/biosustain/potion-client/blob/master/potion_client/resource.py#L155

**Comment by galuszkak** [comment] 2017-03-27 10:55
@rolandjitsu so based on @lyschoening answer I believe he had the same impression as me that save works as upsert. :)

This  can simplify some codebases a lot with `if (id|uri)`  and finding out if object is saved on server or not.

**Comment by rolandjitsu** [comment] 2017-03-27 15:23
@galuszkak Published a new version that adds support for this (https://github.com/biosustain/potion-node/commit/799193062980ecd5954fdae011b180bc891806c0). Try it out and let me know if it works for you.
